# Generated by Django 4.1.7 on 2023-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitura',
            name='dispositivo',
        ),
        migrations.AddField(
            model_name='leitura',
            name='mac',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
