# Generated by Django 4.1.7 on 2023-03-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0003_leitura_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitura',
            name='dispositivo',
        ),
    ]
